export const PHASER_IMPORT_PATH = '../node_modules/phaser/dist/phaser.esm.js';

export const LOGICAL_WIDTH = 320;
export const LOGICAL_HEIGHT = 180;

export const ARENA_OFFSETS = Object.freeze({
  enemy: { x: 0, y: 0 },
  player: { x: 0, y: 0 },
});

export const UI_ASSETS = Object.freeze({
  bgAtlas: { key: 'pkb-ui-bg', json: './assets/pokerogue/ui/bg.json', path: './assets/pokerogue/ui/' },
  promptAtlas: { key: 'pkb-ui-prompt', json: './assets/pokerogue/ui/prompt.json', path: './assets/pokerogue/ui/' },
  typesAtlas: { key: 'pkb-ui-types', json: './assets/pokerogue/ui/misc/types.json', path: './assets/pokerogue/ui/misc/' },
  typesKoAtlas: { key: 'pkb-ui-types-ko', json: './assets/pokerogue/ui/misc/types_ko.json', path: './assets/pokerogue/ui/misc/' },
  categoriesAtlas: { key: 'pkb-ui-categories', json: './assets/pokerogue/ui/misc/categories.json', path: './assets/pokerogue/ui/misc/' },
  teraAtlas: { key: 'pkb-ui-button-tera', image: './assets/pokerogue/ui/button_tera.png', json: './assets/pokerogue/ui/button_tera.json' },
  trayAtlas: { key: 'pkb-ui-pb-tray-ball', image: './assets/pokerogue/ui/pb_tray_ball.png', json: './assets/pokerogue/ui/pb_tray_ball.json' },
  overlayHpAtlas: { key: 'pkb-ui-overlay-hp', image: './assets/pokerogue/ui/overlay_hp.png', json: './assets/pokerogue/ui/overlay_hp.json' },
  overlayMessage: { key: 'pkb-ui-overlay-message', url: './assets/pokerogue/ui/overlay_message.png' },
  overlayExp: { key: 'pkb-ui-overlay-exp', url: './assets/pokerogue/ui/overlay_exp.png' },
  overlayHpLabel: { key: 'pkb-ui-overlay-hp-label', url: './assets/pokerogue/ui/text_images/ko/battle_ui/overlay_hp_label_ko.png' },
  overlayLv: { key: 'pkb-ui-overlay-lv', url: './assets/pokerogue/ui/text_images/ko/battle_ui/overlay_lv_ko.png' },
  overlayExpLabel: { key: 'pkb-ui-overlay-exp-label', url: './assets/pokerogue/ui/text_images/ko/battle_ui/overlay_exp_label_ko.png' },
  numbersAtlas: { key: 'pkb-ui-numbers', image: './assets/pokerogue/ui/numbers.png', json: './assets/pokerogue/ui/numbers.json' },
  window: { key: 'pkb-ui-window', url: './assets/pokerogue/ui/windows/window_1.png' },
  windowThin: { key: 'pkb-ui-window-thin', url: './assets/pokerogue/ui/windows/window_1_thin.png' },
  windowXthin: { key: 'pkb-ui-window-xthin', url: './assets/pokerogue/ui/windows/window_1_xthin.png' },
  cursor: { key: 'pkb-ui-cursor', url: './assets/pokerogue/ui/cursor.png' },
  cursorTera: { key: 'pkb-ui-cursor-tera', url: './assets/pokerogue/ui/cursor_tera.png' },
  menuSel: { key: 'pkb-ui-menu-sel', url: './assets/pokerogue/ui/bmenu_sel.png' },
  pbinfoPlayer: { key: 'pkb-ui-pbinfo-player', url: './assets/pokerogue/ui/pbinfo_player.png' },
  pbinfoEnemy: { key: 'pkb-ui-pbinfo-enemy', url: './assets/pokerogue/ui/pbinfo_enemy_mini.png' },
  pbinfoPlayerType1: { key: 'pkb-ui-pbinfo-player-type1', image: './assets/pokerogue/ui/pbinfo_player_type1.png', json: './assets/pokerogue/ui/pbinfo_player_type1.json' },
  pbinfoPlayerType2: { key: 'pkb-ui-pbinfo-player-type2', image: './assets/pokerogue/ui/pbinfo_player_type2.png', json: './assets/pokerogue/ui/pbinfo_player_type2.json' },
  pbinfoPlayerType3: { key: 'pkb-ui-pbinfo-player-type3', image: './assets/pokerogue/ui/pbinfo_player_type.png', json: './assets/pokerogue/ui/pbinfo_player_type.json' },
  pbinfoEnemyType1: { key: 'pkb-ui-pbinfo-enemy-type1', image: './assets/pokerogue/ui/pbinfo_enemy_type1.png', json: './assets/pokerogue/ui/pbinfo_enemy_type1.json' },
  pbinfoEnemyType2: { key: 'pkb-ui-pbinfo-enemy-type2', image: './assets/pokerogue/ui/pbinfo_enemy_type2.png', json: './assets/pokerogue/ui/pbinfo_enemy_type2.json' },
  pbinfoEnemyType3: { key: 'pkb-ui-pbinfo-enemy-type3', image: './assets/pokerogue/ui/pbinfo_enemy_type.png', json: './assets/pokerogue/ui/pbinfo_enemy_type.json' },
  trayOverlayEnemy: { key: 'pkb-ui-tray-overlay-enemy', url: './assets/pokerogue/ui/pb_tray_overlay_enemy.png' },
  trayOverlayPlayer: { key: 'pkb-ui-tray-overlay-player', url: './assets/pokerogue/ui/pb_tray_overlay_player.png' },
  partyBg: { key: 'pkb-ui-party-bg', url: './assets/pokerogue/ui/party_bg.png' },
  partyCancelAtlas: { key: 'pkb-ui-party-cancel', image: './assets/pokerogue/ui/party_cancel.png', json: './assets/pokerogue/ui/party_cancel.json' },
  partySlotAtlas: { key: 'pkb-ui-party-slot', image: './assets/pokerogue/ui/party_slot.png', json: './assets/pokerogue/ui/party_slot.json' },
  partySlotMainAtlas: { key: 'pkb-ui-party-slot-main', image: './assets/pokerogue/ui/party_slot_main.png', json: './assets/pokerogue/ui/party_slot_main.json' },
  partyPbAtlas: { key: 'pkb-ui-party-pb', image: './assets/pokerogue/ui/party_pb.png', json: './assets/pokerogue/ui/party_pb.json' },
  partySlotHpOverlayAtlas: { key: 'pkb-ui-party-slot-hp-overlay', image: './assets/pokerogue/ui/party_slot_hp_overlay.png', json: './assets/pokerogue/ui/party_slot_hp_overlay.json' },
  partySlotHpBar: { key: 'pkb-ui-party-slot-hp-bar', url: './assets/pokerogue/ui/party_slot_hp_bar.png' },
  partySlotOverlayHp: { key: 'pkb-ui-party-slot-overlay-hp', url: './assets/pokerogue/ui/text_images/ko/party_ui/party_slot_overlay_hp_ko.png' },
  partySlotOverlayLv: { key: 'pkb-ui-party-slot-overlay-lv', url: './assets/pokerogue/ui/text_images/ko/party_ui/party_slot_overlay_lv_ko.png' },
  overlayHpBossAtlas: { key: 'pkb-ui-overlay-hp-boss', image: './assets/pokerogue/ui/overlay_hp_boss.png', json: './assets/pokerogue/ui/overlay_hp_boss.json' },
  pbinfoEnemyBoss: { key: 'pkb-ui-pbinfo-enemy-boss', url: './assets/pokerogue/ui/pbinfo_enemy_boss.png' },
  statusesAtlas: { key: 'pkb-ui-statuses', json: './assets/pokerogue/ui/misc/statuses_ko.json', path: './assets/pokerogue/ui/misc/' },
  shinyIconsAtlas: { key: 'pkb-ui-shiny-icons', json: './assets/pokerogue/ui/shiny_icons.json', path: './assets/pokerogue/ui/' },
  iconTera: { key: 'pkb-ui-icon-tera', url: './assets/pokerogue/ui/icon_tera.png' },
  iconSpliced: { key: 'pkb-ui-icon-spliced', url: './assets/pokerogue/ui/icon_spliced.png' },
  iconOwned: { key: 'pkb-ui-icon-owned', url: './assets/pokerogue/ui/icon_owned.png' },
  abilityBarLeft: { key: 'pkb-ui-ability-bar-left', url: './assets/pokerogue/ui/ability_bar_left.png' },
  abilityBarRight: { key: 'pkb-ui-ability-bar-right', url: './assets/pokerogue/ui/ability_bar_right.png' },
  arenaBg: { key: 'pkb-arena-bg', url: './assets/pokerogue/arenas/grass_bg.png' },
  arenaEnemy: { key: 'pkb-arena-enemy', url: './assets/pokerogue/arenas/grass_b.png' },
  arenaPlayer: { key: 'pkb-arena-player', url: './assets/pokerogue/arenas/grass_a.png' },
});
